### ISSUE TITLE
win11 can`t preview video

### ISSUE THREAD

**Issue by xingsulianhen** [QL-Win/QuickLook#1369] opened 2023-11-27 11:15 UTC
**Describe the bug**
can`t preview video

**To Reproduce**
1.find a .mp4 file
2.spaceBar, display error

**Expected behavior**
play this video

**Desktop (please complete the following information):**
 - Windows 11 Pro N(10.0.22621)
 - QuickLook Version: [QuickLook-3.7.3]

**Screenshots and Exception Log**
![QuickLook_06BlUJbXy1](https://github.com/QL-Win/QuickLook/assets/34211619/23155488-6d6e-4314-8ab7-36199f095176)

**Comment by rabelux** [comment] 2023-11-27 13:43
Duplicate of #921 and #707

**Closed by rabelux** 2023-11-27 13:43 UTC
