### ISSUE TITLE
QuickLook doesn't work with File Explorer's new tabs feature

### ISSUE THREAD

**Issue by effcol** [QL-Win/QuickLook#1174] opened 2022-08-11 15:43 UTC
[Windows released in their Insider Build /Dev Channel an update to file Explorer that allows for tabs within one window, like a web browser.](https://www.ghacks.net/2022/08/11/whats-new-in-windows-11-insider-preview-build-25179/) 
QuickLook no longer works properly with this updated file explorer, when you've got multiple tabs open, QuickLook is confused as to which file on which tab it should show you.
This feature will be filterng through to the main Windows 11 channel relativly soon, so will affect more people then.

Steps to reproduce the behaviour:
1. Be on at least Windows 11 Insider Preview Build 25179
2. Make sure you're on the right Windows version/Windows has downloaded the tabs feature by opening file Explorer and seeing tabs on the top bar.
3. Go to any random folder in File Explorer
4. Open a new tab by pressing the '+' button at the top.
5. Browse to a file you want to view
6. Press space to view the file
7. QuickLook will show you either the folder of file selected in the other tab, never the one in the tab you're currently in, unless you close QuickLook and open it again while int hat tab.
8. If you haven't opened a second tab though, QuickLook continues to work how it should.

 - OS Version: Windows 11 Insider Preview Build 25179
 - QuickLook Version: 3.7.1 (UWP)

[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/9309949/QuickLook.Exception.log)

**Comment by rabelux** [comment] 2022-08-11 16:27
Duplicate of #1153.

**Closed by rabelux** 2022-08-11 16:27 UTC
