### ISSUE TITLE
Issues on W11

### ISSUE THREAD

**Issue by justsaft** [QL-Win/QuickLook#962] opened 2021-07-23 10:27 UTC
**Describe the bug**
These are some issues that occurred to me after upgrading to the Windows Insider dev build:
Titelbar buttons are invisible until you hover over them once,
information about the item is invisible,
the cursor becomes unresponsive as you move the preview window,
If HDR is enabled and you move the cursor it becomes unresponsive until the preview window is closed

**To Reproduce**
1. Be on this Windows build
2. Preview anything with Quicklook

**Expected behavior**
Expected to behave like on Windows 10

**Desktop (please complete the following information):**
 - OS Version: Windows 11 Insider Dev build 10.0.22000.71
 - QuickLook Version: 3.6.11 (UWP) 

**Screenshots and Exception Log**
https://imgur.com/iPEXwT8

**Comment by rabelux** [comment] 2021-07-23 12:01
Duplicate of #955

**Closed by rabelux** 2021-07-23 12:01 UTC
