### ISSUE TITLE
Overexposed rendering error

### ISSUE THREAD

**Issue by MRLEAFYE** [QL-Win/QuickLook#1400] opened 2024-02-28 07:49 UTC
**Describe the bug**
hi，
Maybe I drank too much and put it running in a virtual machine, anyway it went wrong

I installed the software in Windows10 workstation-1909 in the VMware Workstation 16 Pro and found that there was an exposure when using it. The effect is as follows,I tried multiple versions, but it didn't get any better

I also tried other virtual machines and they worked fine in Windows server 2019 ver 1809

**To Reproduce**
when press space bar
It shows like the screenshot

**Expected behavior**
The color is too exposed to read

**Desktop (please complete the following information):**
 - OS Version: Windows 10 1909 on VMware Workstation 16 Pro
 - QuickLook Version:  QuickLook-3.7.3.msi from GitHub 
 - QuickLook Version:  QuickLook-3.6.9.msi from GitHub 
**Screenshots and Exception Log**
![Snipaste_2024-02-28_14-55-39](https://github.com/QL-Win/QuickLook/assets/137371052/18334a5d-d09b-4cc8-9bb8-15f5cd7ca8a2)
![Snipaste_2024-02-28_14-56-03](https://github.com/QL-Win/QuickLook/assets/137371052/11cbb472-da2b-4ef5-b0c6-62fb2e8daf02)
![Snipaste_2024-02-28_14-59-50](https://github.com/QL-Win/QuickLook/assets/137371052/30853535-ac84-476f-9f82-a6061ab6e887)

**Comment by rabelux** [comment] 2024-04-01 20:45
Duplicate of #1334

**Closed by rabelux** 2024-04-01 20:45 UTC
Labels: duplicate

**Comment by xupefei** [comment] 2024-04-02 17:07
Can you try to disable the transparency - https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations#enabledisable-window-transparency-since-v3611-23?

**Comment by MRLEAFYE** [comment] 2024-04-29 11:22
> Can you try to disable the transparency - https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations#enabledisable-window-transparency-since-v3611-23?

Yes,it worked! Thank you very much！
![image](https://github.com/QL-Win/QuickLook/assets/137371052/21092a99-a735-4a4d-8ab2-ab28aff24928)
