### ISSUE TITLE
Missing / Error French translation

### ISSUE THREAD

**Issue by Zazou49** [QL-Win/QuickLook#994] opened 2021-09-19 23:28 UTC
**Describe the bug**
Some words are presents in translation files but still displayed in English.

**To Reproduce**
1. Hover buttons on the top bar

**Expected behavior**
Translated string

**Desktop (please complete the following information):**
 - OS Version: W11
 - QuickLook Version: 3.7 from Winget

**Screenshots and Exception Log**

![image](https://user-images.githubusercontent.com/89610869/133946279-a9107f46-61f1-4fa6-bd09-44a59e0ed8fb.png)
![image](https://user-images.githubusercontent.com/89610869/133946283-e4eff608-d84a-4df2-9ae8-1eb2b65111a6.png)
![image](https://user-images.githubusercontent.com/89610869/133946285-7fed1ce8-fae3-476f-944c-76e4557d072b.png)
![image](https://user-images.githubusercontent.com/89610869/133946287-8eb565d2-3807-4123-8fd4-2517ee01e20f.png)

**Comment by rabelux** [comment] 2021-09-20 09:10
Duplicate of #868

**Closed by rabelux** 2021-09-20 09:10 UTC
