### ISSUE TITLE
Quicklook copies file path in voidtools Everything

### ISSUE THREAD

**Issue by Darthagnon** [QL-Win/QuickLook#593] opened 2019-12-31 14:56 UTC
Steps to reproduce:
1. Copy a text string (e.g. web address)
2. Use [Everything](https://voidtools.com/downloads/) to find a .docx or other editable text file.
3. Navigate to text file in Everything using arrow keys, and press Enter/Return to open it.
4. Ctrl+V paste your clipboard contents. Your text string is now gone, and replaced by the filepath of the opened text file.

[This is apparently a bug in QuickLook, not in Everything](https://www.voidtools.com/forum/viewtopic.php?f=5&t=8687&p=29364#p29364). 

It's very annoying when copying a web address and I try to use my keyboard only to navigate to a notes.docx to paste the web address. It forces me to use my mouse

**Comment by xupefei** [comment] 2020-01-02 16:43
I believe this issue has been fixed in https://github.com/QL-Win/QuickLook/issues/521.
Try the Nightly version.

**Comment by Darthagnon** [comment] 2020-01-04 20:46
I got the nightly version from https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts and so far, so good, looks like it's fixed. I'll update this post if there's any further problems.

**Comment by Darthagnon** [comment] 2020-01-26 16:15
Update: The nightly I installed fixed the "Space copies file path" bug, but it now has another bug, where, as long as QuickLook is running, if I select a file in Everything and Ctrl+X it, the clipboard is cleared after half a second or so.

Is there a new nightly that would have fixed this issue?

**Comment by xupefei** [comment] 2020-02-02 15:42
What does Ctrl+X do in Everything?

**Comment by Darthagnon** [comment] 2020-02-10 19:48
Cuts a file, if a file is selected. Everything uses default Windows Explorer controls in general (Ctrl+C/V/X, Space previews with QuickLook, etc.)

-----------------------
I'm thinking it might have been a one-off bug, as I haven't seen that behaviour since.

**Comment by HASJ** [comment] 2020-03-31 20:10
Any progress on this? Because since QuickLook v3.6.5 and now in v3.6.6, while using Everything, pressing Space does nothing at all.

**Comment by Darthagnon** [comment] 2020-04-02 12:59
@HASJ what OS are you on? It works for me on Win10 v1709; I'll test soon on Win7

**Comment by HASJ** [comment] 2020-04-02 19:01
@Darthagnon Win10 x64 v1909

**Comment by N3pp** [comment] 2020-04-05 22:42
@HASJ Does it work if you run QuickLook as administrator?

**Comment by Darthagnon** [comment] 2020-04-06 12:48
Further tests my end confirm: this issue is not fixed. I can't speak for @HASJ's problem, as QuickLook works for me, but v3.6.6 is back to copying file paths again in Everything (this was fixed for a while in prerelease build QuickLook-3.6.5-37-g2d8a38f).

Example: I copy a web address from browser. I press Ctrl+Alt+Space to open Everything and search for a Word.docx. I navigate to it via keyboard, and open it with Enter. I paste the clipboard into the document. The clipboard pastes the document's file path, not the web address I copied - this issue is caused by QuickLook, as confirmed by Everything's developers. 

QuickLook v3.6.6 is broken again; gonna have to downgrade back to QuickLook-3.6.5-37-g2d8a38f.

**Comment by HASJ** [comment] 2020-04-07 13:47
@Darthagnon I found the issue. If you turn `Everything > Tools > General > Results > Double quote copy as path`, QuickLook can't use the path.

**Comment by xupefei** [comment] 2020-04-08 08:50
QuickLook has to copy the path to be able to work in Everything. In the latest version (3.6.6) of QuickLook:

 * The "copy path" operation will only happen when a user previews a file from Everything.
 * If the user just uses Everything while QuickLook is running, QuickLook will not copy the file path (i.e., will not overwrite the clipboard).

The ultimate solution would be Everything to provide a SendMessage/PostMessage API that returns the full path of the selected file.

**Comment by Darthagnon** [comment] 2020-04-08 11:45
Tested with QuickLook v3.6.7: 
- Copied dankmeme.jpg in \Downloads\
- Ctrl+Alt+Space to open Everything, search for my dank memes folder
- Didn't preview anything with QuickLook. Pressed Enter to open folder.
- dank memes folder opened in Explorer, Ctrl+V to paste the .jpg into the folder.
- Nothing happens. The .jpg has been cleared from the clipboard and replaced with the folder path.

@xupefei Maybe it has something to do with the activation method for Everything? e.g. I use Ctrl+Alt+Space - maybe sometimes, Quicklook grabs that Space and gets confused?

@HASJ What activation key combo do you use for QuickLook? (Off topic, but how did you get QuickLook dark like that?! Looks sweet!)

**Comment by xupefei** [comment] 2020-04-09 07:32
Strange. I tried on my machine but I can't reproduce this issue.
Here is what I did:

1. Install Everything Service.
2. ![image](https://user-images.githubusercontent.com/1687847/78869238-e9647700-7a4c-11ea-89fd-18cd67382f7d.png).
3. Copy some texts.
4. On Desktop, press Ctrl+Alt+Space to bring up the Everything window.
5. Type something, press the Down Arrow key, then press Enter.
6. An explorer window opens.
7. Press Ctrl+V in a notepad, I can see the texts I copied in Step 3.

I an using QuickLook 3.6.7 and Everything  1.4.1.969 (x64). Any comments?

**Comment by Darthagnon** [comment] 2020-04-09 17:53
No idea :'( Thank you for testing! From your post, I realised there's an update for Everything. Maybe that'll change things. It doesn't seem to happen with 100% certainty for me

**Comment by HASJ** [comment] 2020-04-12 09:08
> @HASJ What activation key combo do you use for QuickLook? (Off topic, but how did you get QuickLook dark like that?! Looks sweet!)

`CTRL + Shift + F`. Custom Windows theme named Penumbra, you can get it on DeviantArt.

> @HASJ, what programs do you normally keep running as services & where do you have QuickLook/Everything installed? Maybe there's a common denominator for us.

Default locations and as of v3.6.7, QuickLook only copies the file's path when previewing a file, like xupefei said.
I don't use TidyTabs, no. My issue seems fixed.

**Comment by Darthagnon** [comment] 2020-05-28 10:22
I'm thinking my issue must have been caused by having a Quicklook window open (and hidden) in the background somewhere (which can sometimes happen, when the user forgets about it, or doesn't dismiss it, or "pins" a Quicklook window). Upon searching Everything and navigating with the arrow keys to the target file, Quicklook would update with previews of the highlighted files, _but in the background, out of sight_. This would result in the clipboard being overwritten, without any prompt. 

Workaround: I need to make sure to dismiss Quicklook windows, so they don't stay open in the background and overwrite my clipboard.

**Comment by xupefei** [comment] 2020-05-28 15:29
This is certainly possible, and is the reason why macOS Quick Look window will always be on top of any other windows.

**Comment by K0media** [comment] 2021-04-05 15:05
> ![image](https://user-images.githubusercontent.com/9345660/78676818-5943f780-78bd-11ea-818b-2f63a77c423f.png)
> @Darthagnon @N3pp I found the issue. If you mark `Everything > Tools > General > Results > Double quote copy as path` as on, QuickLook can't use the path.
> Clipboard is still being overwritten, however.

Not related to this issue (completely), but where did you get dark theme for Everything? You did those workaround they're showing in forums or it has been finally rolled out? If it's rolled out, I have to update my build.

Thanks.

(Sorry for OT, just a quick question.)

**Comment by Darthagnon** [comment] 2021-04-06 14:41
@K0media [Penumbra theme on DeviantArt](https://www.deviantart.com/scope10/art/Penumbra-10-Windows-10-visual-style-568740374), requires [UltraUXThemePatcher](https://mhoefs.eu/software_uxtheme.php), will make all of Windows nice and dark.

**Comment by albino1** [comment] 2021-04-06 17:22
@K0media, for what it's worth a Dark Mode/Dark Theme is coming in the next big Everything 1.5 update.  It looks like this and is customizable:

https://www.voidtools.com/forum/viewtopic.php?f=12&t=9789

You can try it out now in the Alpha release, though it's got some bugs:

https://www.voidtools.com/forum/viewtopic.php?f=12&t=9787

**Comment by Darthagnon** [comment] 2021-04-06 20:36
Glad to hear the news about an Everything Dark Mode. Looks like it's getting some other sick improvements, too!

--------------------

It's also worth noting that I haven't noticed the titular bug with folder path copying for quite a while.

**Closed** 2021-12-14 08:11 UTC
