### ISSUE TITLE
markdown文件预览中文乱码 / Mojibake in markdown preview

### ISSUE THREAD

**Issue by Kosette** [QL-Win/QuickLook#976] opened 2021-08-18 13:59 UTC
**Describe the bug**
when previewing .md files which contain Chinese, although the file was encoded with UTF-8 indeed, it still be displayed in GB2312, making the text unreadable.

**To Reproduce**
1. Save [this file](https://raw.githubusercontent.com/renzhezhilu/webp2jpg-online/master/README.md) as .md file
2. use QuickLook preview 
3. Mojibake get

**Expected behavior**
Chinese characters correctly displayed

**Desktop (please complete the following information):**
 - OS Version: [Windows 10 19043]
 - QuickLook Version: [3.6.11 from Windows Store]

**Comment by rabelux** [comment] 2021-08-18 14:45
Duplicate of #877

**Closed by rabelux** 2021-08-18 14:45 UTC
