### ISSUE TITLE
[Feature Request] Folders Preview Add Show File List，Add Lock Window，Thank you！

### ISSUE THREAD

**Issue by sls463** [QL-Win/QuickLook#895] opened 2021-04-11 07:08 UTC
1、Current Folders preview Only Show：Folder Icons、Files Number、File Size
Hope add Show： File List 
Target Demo：
![image](https://user-images.githubusercontent.com/41649803/114295299-fdffa300-9ad6-11eb-9084-abca4816fc09.png)
![image](https://user-images.githubusercontent.com/41649803/114295306-14a5fa00-9ad7-11eb-9ecf-1efe84f722d0.png)

2、Current Only ：Full Screen
Hope add a Button：Lock Window (Lock Window Size + Lock Window Position)
Target Demo：
![image](https://user-images.githubusercontent.com/41649803/114295315-1c659e80-9ad7-11eb-8f00-8b92f09858d1.png)

Window Layout Reference Inspiration：
![Win10](https://user-images.githubusercontent.com/41649803/114295366-62226700-9ad7-11eb-8a5b-1e3b0d83949c.gif)

**Comment by rabelux** [comment] 2021-04-11 11:09
Your first request is a duplicate of #575. You can try it out by installing mooflu's plugin.

**Comment by sls463** [comment] 2021-04-11 11:56
@rabelux
Installing [QuickLook.Plugin.FolderViewer](https://github.com/adyanth/QuickLook.Plugin.FolderViewer/releases/tag/v1.2) Plugin After [Feature Request 1] Resolved ,Thank you！

**Closed** 2024-12-30 13:36 UTC
