### ISSUE TITLE
Dragging preivew window for images causes problems

### ISSUE THREAD

**Issue by brandonwong55** [QL-Win/QuickLook#969] opened 2021-08-05 00:37 UTC
Dragging the preview window for images around will cause a duplicate cursor to appear which is slow to react.

**To Reproduce**
Open an image file and drag the window around

**Expected behavior**
The window should move without lagging and a duplicate cursor should not appear

**Desktop (please complete the following information):**
 - Windows 11 Insider build 22000.100
 - QuickLook Version 3.6.7

**Comment by xupefei** [comment] 2021-08-05 11:51
Duplicate of https://github.com/QL-Win/QuickLook/issues/955.

**Closed by xupefei** 2021-08-05 11:51 UTC
