### ISSUE TITLE
Please add a option to change the font size of the preview

### ISSUE THREAD

**Issue by KMPrg** [QL-Win/QuickLook#1251] opened 2023-01-03 13:43 UTC
Description of the problem
    the font is a bit small, when the text is dense, it is difficult to read.
Desired Solution
    Add an option to resize the text. Of course, since I'm not a professional, you may have a better solution.

Finally, your software is very powerful, thank you very much.

**Comment by rabelux** [comment] 2023-01-03 15:11
Duplicate of #271

**Closed by rabelux** 2023-01-03 15:11 UTC
