### ISSUE TITLE
Windows 10 store version markdown preview Chinese support

### ISSUE THREAD

**Issue by TTTPOB** [QL-Win/QuickLook#426] opened 2018-11-16 03:21 UTC
When previewing .md files, Chinese characters are displayed like tofu.
![image](https://user-images.githubusercontent.com/19909103/48595849-6f33de00-e991-11e8-8a87-4bdb9a8c3001.png)
expected this 
![image](https://user-images.githubusercontent.com/19909103/48595863-7f4bbd80-e991-11e8-9b13-c6673cf788fd.png)
But in other pure text files, Chinese Characters looks pretty normal.
![image](https://user-images.githubusercontent.com/19909103/48595934-b15d1f80-e991-11e8-9ac9-78f9dc2a455b.png)
log
[QuickLook.Exception.log](https://github.com/QL-Win/QuickLook/files/2587857/QuickLook.Exception.log)

**Comment by xupefei** [comment] 2019-01-06 22:33
Can you share the `.md` file with me?

**Comment by TTTPOB** [comment] 2019-01-07 01:11
sure
emmm
![image](https://user-images.githubusercontent.com/19909103/50744223-20e9df80-125c-11e9-9eb4-7c0ce5246cbb.png)
[UCB_NRBC_HSC_methods.zip](https://github.com/QL-Win/QuickLook/files/2731101/UCB_NRBC_HSC_methods.zip)
just change the postfix to .md will do

**Comment by rabelux** [comment] 2021-08-18 15:00
Duplicate of #877

**Closed by rabelux** 2021-08-18 15:00 UTC
Labels: duplicate
