### ISSUE TITLE
Markdown preview do not display emoji

### ISSUE THREAD

**Issue by roose** [QL-Win/QuickLook#758] opened 2020-10-09 10:04 UTC
**Describe the bug**
Markdown preview do not display emoji

**To Reproduce**
1. Create markdown file with emoji
2. See in QuickLook

**Expected behavior**
![изображение](https://user-images.githubusercontent.com/277651/95570563-ecb2dc80-0a48-11eb-905a-c22f0c2d9de0.png)

**Desktop (please complete the following information):**
 - OS Version: Windows 10 2004
 - QuickLook Version: 3.6.10 from Windows Store

**Screenshots and Exception Log**
![изображение](https://user-images.githubusercontent.com/277651/95570521-dad13980-0a48-11eb-9d91-e508cec2a90b.png)

**Comment by rabelux** [comment] 2021-08-18 14:59
Duplicate of #877

**Closed by rabelux** 2021-08-18 14:59 UTC
Labels: duplicate, enhancement

**Comment by roose** [comment] 2021-08-18 18:47
@rabelux duplicate? 😁 Didn't know that an earlier issue might be a duplicate of a later issue .

**Comment by rabelux** [comment] 2021-08-18 20:24
I was already expecting this comment but not that quick! 😄
I chose the issue with the most detailed information to be the main target for discussion.
But agreed, I'll change it.
