### ISSUE TITLE
Bug : System workspace tray icon is blurry

### ISSUE THREAD

**Issue by SakuraNeko** [QL-Win/QuickLook#831] opened 2021-01-29 08:57 UTC
*For all's convenience, please use English to fill this issue.*

![image](https://user-images.githubusercontent.com/22462516/106253382-5f430480-6252-11eb-8def-4193fc7b9196.png)
System workspace tray icon is blurry.

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

A laptop with multiple monitors has a different scale than an external monitor and a built-in monitor. This will cause this problem.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 20H2 19042.782
 - QuickLook Version: 3.6.10 (UWP)

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations]

![image](https://user-images.githubusercontent.com/22462516/106253775-e5f7e180-6252-11eb-8fbe-00c5890fdd8b.png)
Attempting to support a higher level of DPI awareness may resolve the issue.

**Comment by rabelux** [comment] 2022-03-22 08:23
Duplicate of #671

**Closed by rabelux** 2022-03-22 08:23 UTC
