### ISSUE TITLE
Quicklook crashing when previewing large image files

### ISSUE THREAD

**Issue by mbassalbioinformatics** [QL-Win/QuickLook#1059] opened 2021-12-09 23:26 UTC
Hi again
Quicklook 3.7.1 still crashes when trying to open large png files >~3-4Mb in size

_Originally posted by @mbassalbioinformatics in https://github.com/QL-Win/QuickLook/issues/1054#issuecomment-990396555_

**Comment by rabelux** [comment] 2021-12-10 11:42
Duplicate of #1054

**Closed** 2021-12-10 11:41 UTC
