### ISSUE TITLE
Lost focus, when scroll music files

### ISSUE THREAD

**Issue by djmosq** [QL-Win/QuickLook#338] opened 2018-09-04 19:07 UTC
Hello.
Thanks for this cool utility. that i miss on windows based machines.
But i'm very often use it for quick search thru big music collection, so scroll music very often.

When i'm do this on Mac based machines, focus on the finder window still there, and i can press 'space' on music file,  than mouse click in the middle of the song, and than press down arrow, and quicklook will open next file. 
But in Windows, after i click in the middle on the song down arrow dont work, becouse now focus on the QuickLook window, not on the explorer.

Hope you can solve this guys.

Thanks!

**Comment by rabelux** [comment] 2018-09-04 19:54
I'd like to have this point open for discussion, as it kind of conflicts with my expectation of keyboard-input only affecting the window in the foreground. When viewing a large text-file for example (or PDF) hitting the down-button should rather scroll down (expected behavior) than move to the next file (annoying). But I do see the advantage of not having to hit space 2 times for closing, moving down with arrow key, and opening the preview again in your case. So I'd be happy to hear other opinions on this.
Concerning your case: wouldn't it be better to be able to quick-skip let's say 30 seconds by hitting alt+right instead of moving from keys to mouse and back every time? That way you could leave your hands on the keyboard and the time needed for hitting space two times will probably be less than switching input devices

**Comment by djmosq** [comment] 2018-09-04 20:03
@rabelux its like a habit for me to use mouse or touchpad, so left hand on keyboard, right on the mouse, and if music file is needed to move to another folder by drag&drop - my right hand already on the mouse.
Summarize - just want that QuickLook will be the same as Mac OS build in feature, if its possible. Hope yes =)

**Comment by xupefei** [comment] 2018-09-05 19:12
Well, this is partially possible.
In macOS, the arrow key works in the following way:

1) By default, arrows keys switch selected file.
2) If you click in the Quick Look window, then arrows keys will change the preview content, e.g., next page of PDF.
3) If you are now on the last page of PDF and pressing the Down arrow, Quick Look will send this key to Finder, because the PDF has no "next page" to go.
4) The same for texts, images, etc. If the preview window is not able to make any movement to respond to the key, it then sends the key to Finder.

In Windows, what possible are the first two points. It will work like this:

1) By default, arrows keys switch the selected file.
2) If you click in the Quick Look window, then arrows keys will change the preview content, e.g., next page of PDF.
3) If you are now on the last page of PDF and pressing the Down arrow, **QuickLook will do nothing, i.e., not switching to the next file**.
4) The same for texts. If the preview window is not able to make any movement to respond to the key, **it will not switch to the next file**.
5) I tried with Image and Video/Audio. Arrow key can always be send to the underlying File Explorer.

I think that's enough to solve your problem while keeping @rabelux's expectation, ain't they?

**Comment by simioni** [comment] 2020-04-04 07:52
@xupefei Your suggestions would make the arrow keys behave just like they do on Mac OS, which is great and I'd love to see that.


> with Image and Video/Audio. Arrow key can always be send to the underlying File Explorer.

This alone would solve 95% of the problem!

The most frustrating aspect of the current behaviour is interacting with the Quicklook window to seek / zoom a media file, but them completely loosing the ability to navigate to the next / previous.

**Comment by xupefei** [comment] 2020-04-04 13:01
I remember that the behaviour of QuickLook was once the following:

* QuickLook window will never get focus
* Users can only interact with QuickLook window by mouse
* Since QuickLook will never get focus, all keyboard inputs will be handled by the OS

The above no-focus behaviour sounds better than the current one, isn't it?

**Comment by simioni** [comment] 2020-04-05 13:13
@xupefei It does. The mac quick look window never remove focus from finder. You can always use the arrow keys to navigate, even after interacting with the window. That's much more useful.

**Comment by xupefei** [comment] 2020-05-07 20:38
The further discussion goes to #644.

**Closed by xupefei** 2020-05-07 20:38 UTC
