### ISSUE TITLE
Videos are shown with incorrect rotation

### ISSUE THREAD

**Issue by SimJoSt** [QL-Win/QuickLook#762] opened 2020-10-18 22:14 UTC
**Describe the bug**
Record video on a phone in portrait mode. The video is still saved in 16:9 aspect ratio, but a flag is added to play the video in a different rotation. Video players like VLC respect this flag and play the video in the correct orientation. The flag can be inspected with MediaInfo for example.

**To Reproduce**
1. Record video on phone in portrait mode (or have any video with a rotation value not being 0).
2. Open the video in QuickLook

**Expected behavior**
Play the video in the correct orientation.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 2004
 - QuickLook Version: 3.6.10 MSI edition

**Comment by xupefei** [comment] 2020-10-19 07:49
The video viewer already handling roration: https://github.com/QL-Win/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.VideoViewer/ViewerPanel.xaml.cs#L310 so something is going wrong here.
Could you share me a sample video?

**Comment by rabelux** [comment] 2020-11-20 12:05
Closing this due to missing feedback

**Comment by SimJoSt** [comment] 2021-01-04 00:19
@xupefei here is an example video: https://cloud.freiheitswolke.org/s/a9Qs2dPJr5fT6iw (link is active until the end of January)  
I also noticed that videos recorded with a higher frame rate are played in slow motion. I will have to confirm and investigate that. If correct, I will open another ticket.

Sorry for the delay. I'm just getting my GitHub notifications under control.

**Comment by rabelux** [comment] 2021-01-05 17:24
Confirming that some videos don't have the correct rotation. In my case its a video taken from an Iphone 7.
When playing it with VLC the rotation is correct.
Example video:

https://user-images.githubusercontent.com/16120882/103677804-0e0d6100-4f83-11eb-93e0-46a2f6960b79.mp4

**Comment by xupefei** [comment] 2021-01-10 10:21
I'm not able to reproduce this issue with both video samples you provided:
![Untitled](https://user-images.githubusercontent.com/1687847/104120295-ff81c980-5335-11eb-9249-d1ff86cb8d47.png)
Could you confirm?

**Comment by rabelux** [comment] 2021-01-11 14:58
Just downloaded the latest nightly and unfortunately rotation is still wrong.
Any idea what could be the reason?
I'm still on Win 7 but the creator of this issue is on Win 10 so that shouldn't be causing this,

**Comment by xupefei** [comment] 2021-01-11 15:12
@rabelux Have you installed any codec package?

**Comment by rabelux** [comment] 2021-01-11 15:34
No I haven't. Have you?

**Comment by xupefei** [comment] 2021-01-11 21:58
Me neither. Could you try this build to see if it fixes the problem: https://github.com/QL-Win/QuickLook/releases/tag/3.6.6?
I suspect it's due to https://github.com/QL-Win/QuickLook/issues/603.

**Comment by rabelux** [comment] 2021-01-11 23:02
Installed 3.6.6 and the behaviour stays the same. I even uninstalled everything, deleted files from _AppData\roaming_ as I wanted to make sure no old files are present but no success. Might this be another Intel bug - I have an onboard Intel HD Graphics card in my laptop (and a NVIDIA NVS 3100M)

**Comment by SimJoSt** [comment] 2021-01-14 17:26
I can also check, if my system has some anomalies. The only codec I have installed is the H265 support app from Microsoft. Everything else is done via MPC and VLC.  
I have some plugins installed in QuickLook. Could they interfere? But I believe the issue existed before as well.

**Comment by mooflu** [comment] 2021-01-20 05:04
These vids show fine for me, too. While working on https://github.com/QL-Win/QuickLook/pull/818 I noticed that rotation was wrong if the mediainfo lib failed to load. Maybe try the build artifact in that pull request since it changes how the mediainfo lib is loaded (once at the very beginning). If it fails to load now, it'll probably crash and there should at least be a hint in the log file.

**Comment by xupefei** [comment] 2021-01-20 18:52
@mooflu Yeah I am thinking the same. The mediainfo lib may require some C++ Runtime packages to be present. Haven't got any time to check.

**Comment by rabelux** [comment] 2021-01-20 22:20
Hey guys, thx for digging into this. Just installed mooflu's latest artifact and rotation is still the same. No crash, no error logs, so the mediainfo lib seems to be working fine. Is there some way to call the lib on the video and check the output?

**Comment by xupefei** [comment] 2021-01-21 10:34
@rabelux One easy way to check:

1. Download OllyDbg 1.10: http://www.ollydbg.de/.
2. Run OllyDbg, drag MediaInfo x86 DLL (https://github.com/QL-Win/QuickLook/tree/master/QuickLook.Plugin/QuickLook.Plugin.VideoViewer/MediaInfo-x86) into the window.
3. See if it loads correctly, or an error message (DLL not found) pops up.

**Comment by rabelux** [comment] 2021-01-21 14:06
This is what I get:
![grafik](https://user-images.githubusercontent.com/16120882/105357893-c0852b00-5bf5-11eb-94dc-4194bfeb437a.png)

I also downloaded MediaInfo.exe hoping to find out if any c++ runtime is missing (don't know whether that's the right way to do it tho) and running it on my testvideo returns:
`Rotation : 90°`

Anything else I could do?

**Comment by xupefei** [comment] 2021-01-23 20:54
So it seems the DLL can be loaded. I'll send you a simple testing app to further debugging.

**Comment by xupefei** [comment] 2021-01-24 17:32
Can you download this zip file, extract it, and drag an video file onto `ConsoleApp1.exe`? What's the output?

[mediainfo1.zip](https://github.com/QL-Win/QuickLook/files/5862798/mediainfo1.zip)

**Comment by rabelux** [comment] 2021-01-24 23:37
> Can you download this zip file, extract it, and drag an video file onto `ConsoleApp1.exe`? What's the output?

the video with the rotation issue returns `90000`, two other videos i tested return `0`.

**Comment by xupefei** [comment] 2021-02-15 21:54
Reminder to @xupefei.
I'll try to look at this issue in the weekend.

**Comment by xupefei** [comment] 2021-02-21 17:43
On my machine the return value is `90`. No idea why it's different to yours.

**Comment by xupefei** [comment] 2021-02-21 17:50
Could you try https://ci.appveyor.com/project/xupefei/quicklook/builds/37877157/artifacts?

**Comment by rabelux** [comment] 2021-02-21 18:37
Installed it but somehow behaviour is still the same:
![image](https://user-images.githubusercontent.com/16120882/108634864-17438600-747c-11eb-9e7c-c129522ad4e6.png)

**Comment by xupefei** [comment] 2021-02-22 09:49
Oops, my mistake. There's one more place to fix. I'll to it late today.

**Comment by xupefei** [comment] 2021-02-22 20:05
How about this https://ci.appveyor.com/project/xupefei/quicklook/builds/37896062/artifacts?

**Comment by rabelux** [comment] 2021-02-24 09:19
Solved!! Thank you :partying_face:

**Closed by rabelux** 2021-02-24 09:19 UTC

**Comment by SimJoSt** [comment] 2021-03-27 11:59
I can confirm this works now. Great work 💪 🚀

**Comment by Dreamer-4pda** [comment] 2021-10-09 10:54
Have this issue.
Latest build from MS Store.
