### ISSUE TITLE
arrow keyup doesn't work to switch between multiple elements when it opened into second monitor

### ISSUE THREAD

**Issue by apierre55000** [QL-Win/QuickLook#939] opened 2021-06-18 11:37 UTC
hello,

i saw this bug when i open quicklook into another monitor (not the principal) the arrow keyup doesn't work, i know there are bugs into another monitor but i think the arrow keyup is another

**Comment by rabelux** [comment] 2021-06-18 11:51
Can't reproduce. Please be more specific.

**Comment by rabelux** [comment] 2021-06-18 11:53
And you know there is a template, right? This is the second issue you open that doesn't follow the template. Next one will be closed immediately.

**Comment by apierre55000** [comment] 2021-06-18 11:55
when i pressed the space key on my second monitor into windows explorer in details view mode to preview a document for example, quicklook opened but when i pressed bottom arrow to view the next element for example, it doesn't worked

**Comment by rabelux** [comment] 2021-06-18 11:59
Again, can't reproduce. Everything is working fine on my system. Did you change focus to the preview window aka click in it?

**Comment by apierre55000** [comment] 2021-06-18 12:04
no i have the focus into current explorer on the second monitor (the monitor is in expand mode) and plug to my laptop with usb-c

**Comment by apierre55000** [comment] 2021-06-18 12:06
ohhh i find it ! when i launch quicklook from my principal monitor the bug appears into my second monitor but when i launched quikclook from my second monitor the second monitor worked but not the principal

**Comment by rabelux** [comment] 2021-06-18 12:08
Let me guess, you drag the window onto the other monitor? Then the focus is not on explorer anymore.

**Comment by apierre55000** [comment] 2021-06-18 12:16
i did it but the focus seems does'n work event if i clicked on the explorer many times
i dragged my window explorer and hop it works now
it's amazing the bug disappear, i don't understand... it's not the first time that i encouttered that

**Comment by rabelux** [comment] 2021-06-18 12:28
If your issue is solved, would you be so kind to close this?

**Closed** 2021-06-18 12:50 UTC
