### ISSUE TITLE
open HEIC file very slowly

### ISSUE THREAD

**Issue by JaredDC** [QL-Win/QuickLook#889] opened 2021-04-03 15:22 UTC
open HEIC file very slowly
HEIC is the photo take from iPhone/Android phones.
background: I have install the HEIC extensions in the Microsoft Store.

**Comment by rabelux** [comment] 2021-04-03 16:42
Duplicate of #710

**Comment by JaredDC** [comment] 2021-04-03 16:44
OK, get it.

**Closed** 2021-06-09 17:58 UTC
Labels: duplicate
