### ISSUE TITLE
the program occupies too much memory

### ISSUE THREAD

**Issue by Sinyeee** [QL-Win/QuickLook#1250] opened 2023-01-02 12:26 UTC
When the program runs, it occupies too much memory. Windows10, the program occupies about 108Mb of memory. Wish optimize the memory usage.

**Comment by rabelux** [comment] 2023-01-02 14:31
Duplicate of #344

**Comment by Sinyeee** [comment] 2023-01-02 14:31
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Closed by rabelux** 2023-01-02 14:31 UTC
