### ISSUE TITLE
Quicklook Not Working In Windows 10 Pro 22H2

### ISSUE THREAD

**Issue by allenbisconti** [QL-Win/QuickLook#1360] opened 2023-11-15 17:25 UTC
**As of 2 months ago, whenever I hit the spacebar to view anything, I get this popup (see attached screenshot).  I have Windows 10 Pro Version 22H2.  It had been working flawlessly up until 2 months ago.**
![Screenshot 2023-11-15 122346](https://github.com/QL-Win/QuickLook/assets/149194807/c75b2dc6-7b66-458e-8a17-8b9c6e638879)

**Comment by rabelux** [comment] 2023-11-15 18:23
Duplicate of #1354

**Closed by rabelux** 2023-11-15 18:23 UTC

**Comment by allenbisconti** [comment] 2023-11-15 18:39
**@rabelux   I did EVERYTHING you said to do and you closed everything down saying I wasn't doing what you were suggesting.  The reason I didn't get back to you right away after the last thing you had told me to do was because I GOT SICK for almost 2 weeks with the flu, then my wife needed to have surgery.  So I reopened my question because I'm still having the same problem and don't want to have to pay $13 for Seer when I can just get Quicklook working again (somehow).**

**Comment by allenbisconti** [comment] 2023-11-29 20:37
Please delete this thread.
