### ISSUE TITLE
Folder view suggestion

### ISSUE THREAD

**Issue by ghost** [QL-Win/QuickLook#601] opened 2020-01-16 10:34 UTC
I would like to suggest that it would be handy to be able to view whats inside folders, just like you can view whats inside archives.
I know the program "seer" has this, but i prefere quicklook so it would be cool to see this feature here aswell

**Comment by Experien1985** [comment] 2020-01-18 19:17
yes! please!

**Comment by brucefeng10** [comment] 2020-05-14 07:40
Same question as #491

**Comment by rabelux** [comment] 2020-09-24 19:54
Duplicate of #491

**Closed** 2021-09-20 09:25 UTC
Labels: duplicate
