### ISSUE TITLE
WIndows 11 New Tabs Taskbar Support

### ISSUE THREAD

**Issue by EAZY5D** [QL-Win/QuickLook#1170] opened 2022-08-06 21:28 UTC
**Describe the bug**
Um As shown in the picture below, Quicklook opens another file you've selected when you have Multiple tabs opened with the new windows 11  tabs in file explorer mode
![explorer_ThElBeqg8u](https://user-images.githubusercontent.com/55167211/183266168-723a038c-893f-48d4-958c-a77ee94fb772.png)

**To Reproduce**
This is very specific and has to be done in this way 🔽
1. Open File explorer  "Left Tab"
2. Create a new tab with the plus Button "Right Tab" 

If you select smt on the Right Tab and then go to the left, then SELECT a file and try to use Quicklook it previews the previous file selected from the tab on the right.

And yes 100% you have to go to the tab on your right and Deselect.

Now I tried this with 5 tabs and guess what? I had to deselect from all four tabs on my right before I am able to use Quicklook normally from the first tab. 

**Expected behavior**
When I click on smt and press spacebar it just works and pops a preview of what I have selected

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 11  22622. 450]
 - QuickLook Version: [e.g. 3.7.1 from Github]

**Screenshots and Exception Log**
Screenshot
![explorer_ThElBeqg8u](https://user-images.githubusercontent.com/55167211/183266524-81ead9c2-9496-4be4-90b2-fe6b862bc49e.png)

**Comment by rabelux** [comment] 2022-08-07 10:50
Thank you for creating a detailed issue following the template, unfortunately your issue has already been reported. Pls search for existing issues next time.
Duplicate of #1153

**Closed by rabelux** 2022-08-07 10:50 UTC
