### ISSUE TITLE
if file name include char � , it can not be previewed 

### ISSUE THREAD

**Issue by iamqiz** [QL-Win/QuickLook#1376] opened 2023-12-16 23:38 UTC
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**

**To Reproduce**
1.insert char � into a mp4 file name
2.press space when selecting that mp4
3.preview window show message: 
![Snipaste_环境返回_2023-12-17__07-37-17](https://github.com/QL-Win/QuickLook/assets/48077521/0664b875-9c8e-4ad6-99ec-1e0b7913bfec)

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 10 1803]
 - QuickLook Version: [e.g. 0.3.3 from Windows Store]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by rabelux** [comment] 2023-12-17 00:43
Duplicate of #1067 and/or #534

**Closed by rabelux** 2023-12-17 00:43 UTC
