### ISSUE TITLE
office plugin memory leak

### ISSUE THREAD

**Issue by lizardll** [QL-Win/QuickLook#419] opened 2018-11-08 08:46 UTC
**Describe the bug**
Memory leak happens when previewing excel file.

**To Reproduce**
1. use space button to preview a excel file
2. use space to close the current window
3. goto 1

**Expected behavior**
Then you will find the program possesses more and more memory and never free them.

**Desktop (please complete the following information):**
 - OS Version:  Windows 10 1803
 - QuickLook Version: v3.6.4 from msi

**Screenshots and Exception Log**
![image](https://user-images.githubusercontent.com/28426479/48187285-924d0500-e375-11e8-8271-2b49c048ae2d.png)

I don't know why but i can't find the log.

**Comment by youngerruan** [comment] 2018-11-19 08:34
我的也是这样，对了你不用插件可以预览吗，我的好像不能。我记得它上面写了插件给那些没装OFFICE的人用，我装了也不能预览，只能装插件预览
I have met with the same problem, by the way, can you quicklook the office without the plugin? It says that if you install MS office you can quicklook the doc xls or ppt. but i can't.

**Comment by youngerruan** [comment] 2018-11-19 08:34
> **Describe the bug**
> Memory leak happens when previewing excel file.
> 
> **To Reproduce**
> Steps to reproduce the behavior:
> 
> 1. use space button to preview a excel file
> 2. use space to close the current window
> 3. goto 1
> 
> **Expected behavior**
> Then you will find the program possesses more and more memory and never free them.
> 
> **Desktop (please complete the following information):**
> 
> * OS Version:  Windows 10 1803
> * QuickLook Version: v3.6.4 from msi
> 
> **Screenshots and Exception Log**
> ![image](https://user-images.githubusercontent.com/28426479/48187285-924d0500-e375-11e8-8271-2b49c048ae2d.png)
> 
> I don't know why but i can't find the log.

我的也是这样，对了你不用插件可以预览吗，我的好像不能。我记得它上面写了插件给那些没装OFFICE的人用，我装了也不能预览，只能装插件预览
I have met with the same problem, by the way, can you quicklook the office without the plugin? It says that if you install MS office you can quicklook the doc xls or ppt. but i can't.

**Comment by lizardll** [comment] 2018-11-20 14:13
以前不用装插件就可以预览office的，最近几个月更新之后就不行了，只能装插件。

In the past, I can preview the office files without installing a plug-in. After an update in recent months, it's not working. I have to install plug-ins to get things work.

**Comment by youngerruan** [comment] 2018-11-20 14:18
好的，谢谢你！
Ok, thank you!

**Comment by lizardll** [comment] 2018-12-05 10:21
> 好的，谢谢你！
> Ok, thank you!

而且我发现在我的电脑上v0.3.5也就是没有插件的版本运行更快，视觉效果也更好
And I found that on my computer v0.3.5, that is, the version without plugins runs faster and the visual effect is better.

**Comment by youngerruan** [comment] 2018-12-05 11:21
好！我试试，我目前用的是UWP版本，方便更新。
再次感谢。
OK! i will have a try, now i am using UWP version which is easy to update.
And thank you again.

**Comment by Mario-Hofstaetter** [comment] 2018-12-27 22:51
> Steps to reproduce the behavior:
> 
>     1. use space button to preview a excel file
>     2. use space to close the current window
>     3. goto 1
>
> Then you will find the program possesses more and more memory and never free them.

This seems to be reproducible with docx files too.

```
OS: Win 10 x64 1809 17763.195
Quicklook: v3.6.4
msi Version installed via chocolatey
OfficeViewer v2 Installed
```

I installed the OfficeViewer plugin because the preview for office did not work although Office 2019 is installed.

**Comment by emannxx** [comment] 2019-01-18 17:53
I can confirm this error. Opening, for instance, a very large excel file will cause the app to use lots of RAM - closing QL doesn't release said RAM (in fact, if the file is previewed again, it will use even more RAM, non stop). 
![1](https://user-images.githubusercontent.com/6955982/51403956-f3e5d880-1b49-11e9-99f3-3886db391b60.jpg)
![2](https://user-images.githubusercontent.com/6955982/51403961-f5af9c00-1b49-11e9-96b3-7f103139a39d.jpg)
![3](https://user-images.githubusercontent.com/6955982/51403963-f811f600-1b49-11e9-8af9-56a327cdd135.jpg)

**Comment by emako** [comment] 2024-12-17 14:57
Outdated issue

**Closed by emako** 2024-12-17 14:57 UTC
