### ISSUE TITLE
Down-arrow won't move on from an Excel file

### ISSUE THREAD

**Issue by DavidPaulNZ** [QL-Win/QuickLook#314] opened 2018-08-09 19:25 UTC
**Describe the bug**
In File Explorer viewing Detailed List of files.  I press Space and QuickLook panel activates.  I use the down-arrow key to progressively quick-view each file.  When I get to an Excel file, the down-arrow stops working (QuickLook won't move onto the next file).

**Desktop (please complete the following information):**
 - OS Version: Windows 10.0.17134
 - QuickLook Version: Don't know how to find this.  Downloaded today from Microsoft Store.

**Comment by xupefei** [comment] 2018-08-09 19:34
It is a known issue that some versions' of Excel previewer will steal your keyboard focus. You may try installing/upgrading to a different version of Office, but, unfortunately, I can not promise you anything because this issue is caused by the buggy Excel software which can only be fixed by Microsoft themselves.

Related to #94.

**Closed** 2018-09-02 10:35 UTC
