### ISSUE TITLE
[feature request] remember QuickLook window's size and position

### ISSUE THREAD

**Issue by leConce** [QL-Win/QuickLook#1078] opened 2022-01-26 21:30 UTC
Hi again 
After closing QuickLook it always starts near the Explorer's window from where it was called.
It would be great to have an option to remember the window's last size and position.
In a three monitors environment, I could always navigate the Explorer in one monitor and see the result and displayed file in another.
Thanks for your attention.

**Comment by rabelux** [comment] 2022-01-26 23:10
Duplicate of #608

**Closed by rabelux** 2022-01-26 23:10 UTC
