### ISSUE TITLE
Suggestions for preview folders

### ISSUE THREAD

**Issue by wuxr131** [QL-Win/QuickLook#740] opened 2020-09-21 07:09 UTC
**Is your feature request related to a problem? Please describe.**
When preview a folder, can you just list the contents of the folder instead of just displaying the status of the folder

**Comment by rabelux** [comment] 2020-09-21 12:33
please refer to #491 & #575 and search for existing issues next time. If you comment there the dev still sees it and maybe he will think about adding it if no volunteer can be found.
Also duplicate of #702,  #601, #522

**Comment by Geeyun-JY3** [comment] 2020-09-21 14:22
@rabelux Why not add a duplicate tag? There are too many duplicate issues.

**Comment by rabelux** [comment] 2020-09-21 14:54
I have no rights in this repo. I'm just a fan of this software trying to reduce work for @xupefei as he is the dev.

**Comment by Geeyun-JY3** [comment] 2020-09-21 15:19
> I have no rights in this repo. I'm just a fan of this software trying to reduce work for @xupefei as he is the dev.

Fine😅.

**Comment by xupefei** [comment] 2020-09-21 18:38
@rabelux I'm more than happy to add you as a maintainer :)

**Comment by rabelux** [comment] 2020-09-21 19:04
Unfortunately I can't be of any help regarding the codebase but if managing issues does help you I would gladly accept ;)

**Comment by kak8gm** [comment] 2021-01-18 08:37
It would be really nice to be able to have previews for folders.
A nice concept for that is already available on [reddit](https://www.reddit.com/r/Windows_Redesign/comments/ksdp49/inspired_a_bit_by_quick_look_on_macos_when_the/)
I hope some day it will become a Quicklook feature.
![Folder preview](https://user-images.githubusercontent.com/71850180/104891122-2ca72b00-5979-11eb-87d2-780925d4cf5e.PNG)

**Closed** 2021-09-20 09:21 UTC
Labels: duplicate
