### ISSUE TITLE
win11 文件管理器多窗口预览错误问题

### ISSUE THREAD

**Issue by GuoJikun** [QL-Win/QuickLook#1186] opened 2022-09-28 08:02 UTC
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported?*

**Describe the bug**
A文件管理器打开两个窗口，两个窗口中都选中一个文件，在预览窗口中显示的内容是一样的

**To Reproduce**
1. 文件管理器打开两个窗口，两个窗口中都选中一个文件
2. 在两个窗口中预览显示的内容是一样的

**Expected behavior**

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 11 22H2]
 - QuickLook Version: 3.7.1 from github release

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations](https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by Magician-MO** [comment] 2022-10-24 02:24
+1

**Comment by Kosette** [comment] 2022-10-26 17:58
如果是打开多个窗口，各个窗口切换预览是正常的，只在同一个窗口的多个标签页之间有问题，除非手动取消某个预览过的文件的选定状态，否则切换标签页预览的始终是该文件。

**Comment by vito0719** [comment] 2022-10-28 00:59
+1

**Comment by uvery9** [comment] 2022-11-02 14:44
Duplicate of https://github.com/QL-Win/QuickLook/issues/1153. 
AND We should use English instead of Chinese.

**Closed** 2022-11-02 16:53 UTC
