### ISSUE TITLE
Allow QuickLook to be set as the default program for various file types

### ISSUE THREAD

**Issue by JacobDB** [QL-Win/QuickLook#1273] opened 2023-02-27 16:03 UTC
**Is your feature request related to a problem? Please describe.**
I'd like to use QuickLook as the default app for opening certain file types, similar to how Preview works on MacOS. For example, when double clicking an attached PDF file in Outlook, I'd prefer it to open in QuickLook rather than Edge.

**Describe the solution you'd like**
Registering QuickLook as an "opens with" target, so that file types can be manually configured to open with it, should do the trick

**Describe alternatives you've considered**
Manually opening files with QuickLook

**Additional context**
N/A

**Comment by rabelux** [comment] 2023-02-27 16:18
Duplicate of #334

**Closed by rabelux** 2023-02-27 16:18 UTC
