### ISSUE TITLE
Make ink visible when previewing PDF's with ink annotations

### ISSUE THREAD

**Issue by victorolet** [QL-Win/QuickLook#805] opened 2021-01-06 02:41 UTC
First, want to say thanks for making this software. It's such a big productivity boost! I wanted to suggest if you can make the ink on PDF documents visible on preview? I ink a lot on my device (Surface Go with Surface Pen) and it would be helpful to see my ink notes on preview as well. Currently, previews show as if the document was not inked. This would be a great add if possible. Thanks again for making QuickLook!

(Here is an image for demonstration too)
![image](https://user-images.githubusercontent.com/55980431/103722765-a94a1900-500b-11eb-825c-623e6bcb14ce.png)

**Comment by rabelux** [comment] 2021-01-07 12:29
Duplicate of #672, #421 and #465. Please make use of the search-function next time.

**Comment by victorolet** [comment] 2021-01-07 12:33
My apologies. I did search, but I searched 'ink' and not 'annotations'. Thanks for looking into it.

**Closed** 2021-01-10 11:14 UTC
Labels: duplicate

**Comment by victorolet** [comment] 2021-04-09 02:03
Thank you for fixing this. It's very useful for my work. Very much appreciated!
