### ISSUE TITLE
Hide Icon from system tray

### ISSUE THREAD

**Issue by lukaszjablonski** [QL-Win/QuickLook#729] opened 2020-08-28 08:53 UTC
Would that be possible to have an option to hide the application icon in system tray?

**Comment by rabelux** [comment] 2020-08-28 09:32
aaaand another duplicate of this topic.
Maybe look at #191, #231, #323, #368, #393, #596

**Comment by GoldRenard** [comment] 2020-09-12 07:50
Aaaaaand this is an actual proof what a lot of people **wants this**. So why not to add it? 

Just add it at least as some command line option for advanced users who knows that they are doing and will not complain about "ooooh, how I can quit that program????". 

1. If someone knows how to run program with command line option, they are definitely know how to terminate this program using task manager or even taskkill. Believe me.
2. If someone wants this running without any tray icons, this just means that they want to get it running permanently in background just as part of their OS and don't want to close it at all.

"There will be no way to quit QuickLook" is not an excuse, c'mon.

**Comment by xupefei** [comment] 2020-09-12 11:38
Fair enough. I'll add a configuration.

**Comment by rabelux** [comment] 2020-09-12 12:35
I agree that closing Quicklook is a scenario that pretty much never happens.
I personally like the icon because it assures that Quicklook is still running as crashes sometimes/rarely silently occur.
Just keep that in mind.

> Aaaaaand this is an actual proof what a lot of people wants this

No, this just means people are too lazy to look for existing issues and the same topic has to be discussed at numerous different locations

**Closed** 2020-09-13 21:19 UTC

**Comment by xupefei** [comment] 2020-09-13 21:32
You can now hide the icon by using the latest Nightly build ([download here](https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts)) and setting `ShowTrayIcon` to `false`: https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations#hide-the-tray-icon-since-v3610.

> I personally like the icon because it assures that Quicklook is still running as crashes sometimes/rarely silently occur.

This is actually my main argument to refuse this change 😂
