### ISSUE TITLE
Windows 11 / Tabbed Explorer Support

### ISSUE THREAD

**Issue by jameslashmar** [QL-Win/QuickLook#1153] opened 2022-06-16 17:06 UTC
On Win 11 22621.160 (beta) after enabling tabbed explorer via (https://pureinfotech.com/enable-tabs-file-explorer-windows-11/).  QuickLook works fine initially, but gets a little confused.

So if I have a few explorer tabs open and hit space to preview a file, QuickLook try to preview another file from another tab.  The only way to fix this is to close explorer and reopen it, which at the minute, there is no option to re-open last tabs.

I understand this is not working on technically an unrealised OS, but I LOVE QuickLook and I think this is worth investigating for when tabbed explorer windows are public.

I've tried going to the previous tab and de-selecting the item that is wrongly being quicklooked and also moving the windows tabs around but neither fixes it.

Thanks

**Comment by Tuba202** [comment] 2022-06-26 02:54
Same thing happening to me. Took me a while to realize that it was previewing a file from another tab, as for a bit it just seemed completely ramdom!

**Comment by ashergz** [comment] 2022-08-06 16:18
So I see this has been up for a while and you're aware of it. Do you plan on adding support?

**Comment by SubhoBoy** [comment] 2022-08-06 17:13
One thing I noticed was that QuickLook tries to preview the last selected item, whichever tab it may be in. So if you make sure to deselect all selected items when you switch to another tab, the app should work fine.

Of course, this is just a crude workaround. If you close a tab before deselecting all items in it, QuickLook seems to break until you reopen the window.

**Comment by Tuba202** [comment] 2022-08-06 18:57
Yeah, the unselecting trick doesn't ALWAYS work for me... I've found that sometimes, instead of switching the preview over, it just shows the preview of the whole second tab folder.

**Comment by xupefei** [comment] 2022-08-12 15:34
I think you should ping Microsoft to fix their problem. IMO this issue is caused by the wrong window focus for grouped windows.

**Comment by jameslashmar** [comment] 2022-08-13 11:08
I'm happy to do this, but surely it is in your interest for your app to
work?

Also I'm just a user and don't know the specifics of what to report to them
or where to report it.  If you start the thread, I'm happy to post and
confirm that I'm also receiving the issue.

**Comment by Ryo-Sajima** [comment] 2022-11-01 03:35
With the official release of Windows 11 22H2, some machines have the file explorer tab feature enabled by default. This issue should be fixed as soon as possible.

**Comment by xupefei** [comment] 2022-11-02 16:53
I need to update my machine to 22H2 and then start looking at this.
I'll see if I can find some time this weekend.

**Comment by xupefei** [comment] 2022-11-04 09:06
Update: I know why it doesn't work and figured out a fix. Will try it out over the weekend.

**Comment by xupefei** [comment] 2022-11-05 17:24
Fixed in https://github.com/QL-Win/QuickLook/releases/tag/3.7.2.
Enjoy :)

**Closed by xupefei** 2022-11-05 17:24 UTC

**Comment by GuoJikun** [comment] 2024-10-16 08:57
@xupefei Can you tell me the fixed commit link or pr link?
