### ISSUE TITLE
RAF files are pixelated

### ISSUE THREAD

**Issue by 1570NetworkAdmin** [QL-Win/QuickLook#1335] opened 2023-08-03 14:29 UTC
When I preview RAF files, they're pixelated as if it never fully renders the image.

**Comment by rabelux** [comment] 2023-08-03 17:07
Duplicate of #754

**Closed by rabelux** 2023-08-03 17:07 UTC

**Comment by 1570NetworkAdmin** [comment] 2023-08-15 13:22
> Duplicate of #754
I don't see how these two are related. RAF files don't fully load.
