### ISSUE TITLE
[Feature request] Auto advance to next file after delete

### ISSUE THREAD

**Issue by Waleedov** [QL-Win/QuickLook#1414] opened 2024-04-07 16:43 UTC
If I delete a file (ex: image) then it should auto-advance to the next file. or image.
Right now, when I delete a file, it doesn't go away and the same image stays on the screen.

**Comment by rabelux** [comment] 2024-04-07 17:45
Duplicate of #850

**Closed by rabelux** 2024-04-07 17:45 UTC
