### ISSUE TITLE
Not viewing correct file with the new windows 11 22h2 file explorer tabs

### ISSUE THREAD

**Issue by AMSTools** [QL-Win/QuickLook#1194] opened 2022-10-18 12:09 UTC
*For all's convenience, please use English to fill this issue.*

*Please search within existing issues before the submission. Has this issue already been reported? *

**Describe the bug**
if viewing a preview of a file with the app when more than one tab open in windows 11 file explorer tabs and switching to any other tab and trying to preview any file, the app displays the preview of the first file previewed and not refreshing even if terminated the app and run again.

**To Reproduce**
1. Open windows 11 file explorer
2. preview any file with the app
3. open a new tab in file explorer
4. preview any file with the app
5. the app preview the file from the first tab opened not current file

**Expected behavior**

**Desktop (please complete the following information): **
 - OS Version: [Windows 11 22H2 22621.674]
 - QuickLook Version: [3.7.1]

**Screenshots and Exception Log**
If applicable, add screenshots and logs to help explain your problem. The log file is located in [one of several locations] (https://github.com/QL-Win/QuickLook/wiki/Differences-Between-Distributions#user-data-location).

**Comment by rabelux** [comment] 2022-10-18 15:51
Duplicate of #1153

**Closed by rabelux** 2022-10-18 15:51 UTC
