### ISSUE TITLE
Playback Speed for Video Files (and maybe also for animated images like webp and gifs)

### ISSUE THREAD

**Issue by 0lm** [QL-Win/QuickLook#855] opened 2021-02-27 20:24 UTC
*For all's convenience, please use English to fill this issue.*

**Additional context**

I really love being able to Quick view files. But I was always missing something. Is it possible to add a feature that allows us to set a playback speed when quick viewing videos/gifs/webp files etc....? This is basically for... let me explain this way: You have video files or gif files etc. The thumbnails of these files on Windows 10 are rather bad and maybe show only black color (like the beginning of a movie, the start of this video file is usually black). And the name sof the videos also dont tell you much about the file itself. So you need a way to quickly determine which video this one was etc. But always needing to look through the video via the controls can be annoying. It would be so useful if it was possible to make video files, gif animation, webp file etc. play alot faster so you can quickly and comfortable see what video/animation this one was.

Does this feature request makes sense? Im not sure how many people need something like this, but this would be a great alternative to the missing animated video thumbnails on Windows 10. (like on Youtube, when you hover with your mouse over a video, it shows parts of what this video contains as an animated thumbnail. Windows Explorer cant do this and I couldnt find any explorer which can do this yet.) So if QuickLook could give us a configurable playback speed, this would be a great alternative.

(And besides, anyone know of a plugin for QuickLook so it can play webp animated images? I only found one for the Mac but not for the Windows QuickLook)

**Comment by chiragasawa** [comment] 2021-03-31 12:24
did any one find how to implement this feature ?

**Comment by rabelux** [comment] 2021-03-31 12:52
duplicate of #780. Closing this as the dev mentioned he doesn't see the need for this feature. But he's usually open for pull requests, so if you manage to implement it feel free to file one.

**Closed by rabelux** 2021-03-31 12:52 UTC
Labels: enhancement
