### ISSUE TITLE
QuickLook and "Files"

### ISSUE THREAD

**Issue by mreed4** [QL-Win/QuickLook#1112] opened 2022-03-21 01:41 UTC
**Describe the bug**
The wonderful little tool that is QuickLook does not work with the wonderful tool that is [Files](https://github.com/files-community/Files). At some point it did, then [presumably after an update to Files] it did not. It still works when using the vanilla Explorer.exe.

**To Reproduce**
1. Use "Files" to view the directories on your computer
2. Navigate to an image that you want to view
3. Press "Space"

**Expected behavior**
While using "Files", the QuickLook window should appear, showing the image that the user wants to preview.

**Desktop (please complete the following information):**
 - OS Version: Windows 10 Pro 21H2
 - QuickLook Version: 3.7.1.0 [Windows Store]

**Comment by rabelux** [comment] 2022-03-21 05:33
Duplicate of #1104.
Please search for existing issues before creating new ones!

**Closed by rabelux** 2022-03-21 05:33 UTC
