### ISSUE TITLE
Support for Files app

### ISSUE THREAD

**Issue by ashergz** [QL-Win/QuickLook#1156] opened 2022-07-06 04:16 UTC
Files, the most popular explorer alternative on the Windows store, doesn't seem to support OneQuick as of this moment, and I am not sure if the issue is on their front or with QuickLook. That project is also open source and it would be great someone can take a look to see what it would take to make QuickLook work with Files. The git link for your reference: https://github.com/files-community/Files

**Comment by rabelux** [comment] 2022-07-06 08:51
Duplicate of https://github.com/files-community/Files/issues/9503

**Closed by rabelux** 2022-07-06 08:51 UTC
