### ISSUE TITLE
[feature request] pdf continuous paper scrolling

### ISSUE THREAD

**Issue by leConce** [QL-Win/QuickLook#1077] opened 2022-01-26 19:50 UTC
Hi
Viewing a several pages pdf file scrolls one page at a time.
It would be great to have an option to turn single page on/off  ( to continuous) to view the pages in one long column for easy scrolling instead of viewing one page at a time.
Thanks for your attention

**Comment by rabelux** [comment] 2022-01-26 23:12
Duplicate of #478

**Closed by rabelux** 2022-01-26 23:12 UTC
