### ISSUE TITLE
Markdown supports latex preview

### ISSUE THREAD

**Issue by codezijie** [QL-Win/QuickLook#752] opened 2020-10-03 06:30 UTC
如题，希望markdown预览能够支持latex

Hopefully markdown preview supports latex

**Comment by Justaphysicsnerd** [comment] 2020-10-06 13:39
same as #639

**Comment by rabelux** [comment] 2020-10-06 22:19
Duplicate of #639

**Comment by emako** [comment] 2024-12-31 02:08
This feature should have been implemented in the nightly build (I have not tested it)

https://github.com/QL-Win/QuickLook/releases

If there are any issues, continue to track them

**Closed by emako** 2024-12-31 02:08 UTC
Labels: duplicate
