### ISSUE TITLE
Remember the preview window size!

### ISSUE THREAD

**Issue by thefujunjie** [QL-Win/QuickLook#1196] opened 2022-10-21 06:49 UTC
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thefujunjie** [comment] 2022-10-21 06:50
Is there any way to rememer the size of preview windows for .doc, .pdf, etc. ?
It is annoying to adjust the size of window every time.

**Comment by rabelux** [comment] 2022-10-21 07:09
Duplicate of #1078

**Closed by rabelux** 2022-10-21 07:09 UTC
