### ISSUE TITLE
"Prevent Closing" setting not saved

### ISSUE THREAD

**Issue by aviscaerulea** [QL-Win/QuickLook#1357] opened 2023-10-31 08:12 UTC
**Describe the bug**

If I click "Prevent Closing" on my QuickLook window and then remove focus, it will not close.
Also, when I open QuickLook in preview again, the settings are not saved and are back to OFF.
"Stay on Top" will be saved.

**To Reproduce**

1. Open any file in QuickLook
1. Click on "Prevent Closing
1. Close QuickLook
1. Open the same file in QuickLock

**Desktop (please complete the following information):**

 - OS Version: Windows 10 Pro 22H2
 - QuickLook Version: 3.7.3 (msi) from GitHub

**Comment by rabelux** [comment] 2023-10-31 22:12
What you're describing is 100% intended behaviour. The "prevent closing" feature might be better named "pin window" or something similar. It means you're freezing the window and disconnecting it from the file selection. You can have multiple windows pinned and you have to close each one individually. Therefore it wouldn't make sense to invoke a preview with that setting already being set. What was your expectation?

**Closed by rabelux** 2023-10-31 22:12 UTC
