### ISSUE TITLE
Blur effect doesn't work in Windows 11

### ISSUE THREAD

**Issue by Super12138** [QL-Win/QuickLook#1161] opened 2022-07-24 01:36 UTC
### Describe the bug:
In Windows 11, the blur effect of the preview background does not work, there is only a solid color background (like dark gray or white).

### Steps to reproduce the behavior:
1. Choose a file.
2. Press the space bar.
3. Then you will find that the background does not appear blurred.

### Expected behavior & Suggest:
Windows 11's mica effect can be supported, or it can let the user customize the background (like mica, blur, or a custom background image).

### Desktop:
- OS Version: Windows 11 Insider Preview 22H2 25163.1000
- QuickLook Version: 3.7.1 (UWP) from Windows Store

### Screenshot of the problem:
![Background is not blurred](https://user-images.githubusercontent.com/70494801/180628846-34e3f0ab-4f22-4d36-b005-b23a8bdf19a2.png)

**Comment by rabelux** [comment] 2022-07-24 09:12
Duplicate of  #1147. Should be fixed in the nightly.

**Closed by rabelux** 2022-07-24 09:12 UTC
