### ISSUE TITLE
[Feature Request] Add search support

### ISSUE THREAD

**Issue by persep** [QL-Win/QuickLook#1431] opened 2024-05-29 08:48 UTC
Hi,

I would like to have a "search" function for text in Quicklook.

I would open a text file, for example, with QuickLook and use a search function to search for a certain string all in the same program.
Could it be possible?

Thanks

**Comment by rabelux** [comment] 2024-05-29 09:30
Duplicate of #787 and already fixed

**Closed by rabelux** 2024-05-29 09:30 UTC
