### ISSUE TITLE
Folder preview

### ISSUE THREAD

**Issue by adyanth** [QL-Win/QuickLook#575] opened 2019-11-13 11:46 UTC
When previewing a folder, it is way better to show contents of the folder along with those macOS like folder dropdown (with a triangle to click to expand the folders) rather than showing the last modified which is almost useless information.

Seer does this as well, but well, it is paid.

**Comment by xupefei** [comment] 2019-11-13 19:49
It is actually quite easy to write a plugin for previewing folders based on existing codes of the `ArchiveViewer`, but unfortunately no one want to contribute...

**Comment by rabelux** [comment] 2020-09-24 19:48
duplicate of #491

**Comment by mooflu** [comment] 2021-01-02 22:11
I took a stab at it here: https://github.com/QL-Win/QuickLook/compare/master...mooflu:origin

Not sure I like it. Maybe useful when scanning a bunch of items/folders.
For the single case it's not really any better than opening folder in explorer.

Maybe if it was more like OSX stacks grid and the QL window opened up near the folder as a way to quickly access an item and QL windows closes once you open/select an item.

**Comment by adyanth** [comment] 2021-01-03 01:48
It is helpful since 1. Quicklook opens faster/smoother than explorer 2. When you want to open a deeply nested file/folder, double clicking 10 times is a pain, and you cannot see the contents of the previous folder at the same time.

@xupefei Do you have a README for the build so I can try it out (New to C# and windows app dev in general here 😅)? Or if you can build a nightly by taking a pull request from @mooflu here?

**Comment by adyanth** [comment] 2021-01-03 02:23
It is working great @mooflu @xupefei !
I forked this and added mooflu's branch [here](https://github.com/adyanth/QuickLook/tree/folder-preview) and saw that you have appveyor setup, so made a free account and here is the [build artifacts](https://ci.appveyor.com/project/adyanth/quicklook/builds/37082191/artifacts).

One small issue I noticed, the shortcut files don't show their icons, which I can confirm even the Archive Previewer does not. So, this is looking damn good! Thanks @mooflu and @xupefei please check if this can be added as a core functionality in the next release 🥳

**Comment by adyanth** [comment] 2021-01-03 03:04
Can you think of a way to open the folder on double click or maybe enter? This is helpful if you have already gone down the rabbit hole of folders and want to open one of those in explorer. I see that the double click it tied to opening the top folder, and there are global hooks to Enter. Maybe a possibility of a right click?

**Comment by xupefei** [comment] 2021-01-03 10:28
@mooflu Great work and thanks for @adyanth's build 👍 
Minor comments:
- When previewing a Drive (e.g. `C:\`) the counting is very slow. Maybe to ignore Drives in the Plugin interface (return `false` when `Path.GetPathRoot(path) == path`)?
- I suggest to move the plugin to a standalone repo forked from https://github.com/QL-Win/QuickLook.Plugin.HelloWorld. This allows further dead code removal (remove codes only used in the ArchiveViewer) a standalone distribution of this new plugin.

> the files don't show their icons

The ArchiveViewer is designed to show the default icon of each file type since getting the real icon needs to decompress files. For this new plugin, it is possible to get real icons at the cost of delaying loading speed, unless icons are shown in a async way.

**Comment by adyanth** [comment] 2021-01-03 11:19
It is reasonably fast (~1-2s) on my D: drive which is larger and containing more data than C: but yes, very slow on C: due to the sheer count of files there. Yeah, stopping it for root filesystems would help.

I will try my hands on C# dev with this then, will try to create a module from hello world. (Not sure how forking that is useful, but will use it as a template)

**Comment by mooflu** [comment] 2021-01-03 19:08
A folder-preview plugin sounds right. Not sure if an external plugin makes debugging harder - it was nice to run the whole thing in debug mode. I guess that's mostly bundling and I could keep a branch with the new plugin inside the main project.

Re: opening folder in explorer. 
It currently saves the full path only for files and the click handler checks if a file exists before it opens it.
So it should be easy to allow folders: add full path for folders and remove file check since we know it exists. 
Default for double click is to open the tippy, so it may be a bit surprising when it opens the folder externally. 
Probably ok, though, since you can still open by clicking the tippy icon or right arrow via keyboard.

Re: folder scan
It would be better if it dynamically loaded as you tippy open a folder.

**Comment by xupefei** [comment] 2021-01-03 19:27
> Not sure if an external plugin makes debugging harder - it was nice to run the whole thing in debug mode

Debugging a plugin is not harder:

1. Set the plugin build path to `Debug\QuickLook.Plugins\QuickLook.Plugin.FolderViewer\` (to maintain the dir structure -- QL loads plugins from this folder).
2. Copy a QuickLook executable (with dependencies) to `Debug\`.
3. In plugin debugging tab, set executable to `Debug\QuickLook.exe`.
4. Start a debugging. VS will attach to `QuickLook.exe` and pause at any breakpoint in the plugin code.

**Comment by mooflu** [comment] 2021-01-04 02:20
I've made some of the suggested changes.
- FolderViewer as its own plugin
- no preview when it's the root
- double click (or enter) on folder opens it in explorer
- use "real icons"

WIP here: https://github.com/mooflu/QuickLook/tree/folder-preview/QuickLook.Plugin/QuickLook.Plugin.FolderViewer

**Comment by adyanth** [comment] 2021-01-04 10:17
@mooflu That was quick and impressive! 
I am messing with what you have written, and I don't see a way to either use the QuickLook's keyboard hook or closing the panel once the double click handler runs on the Plugin/FileListView. Any idea what can be done here?

Here is the [repo](https://github.com/adyanth/QuickLook.Plugin.FolderViewer) separated and cloned from the HelloWorld plugin, and the qlplugin [here](https://github.com/adyanth/QuickLook.Plugin.FolderViewer/releases/tag/v1.0) if anyone wants to try!

**Comment by mooflu** [comment] 2021-01-04 19:03
@adyanth Thanks for making a separated version. The readme says it's MIT but the source code is GPL. The is also true for the hello world plugin which uses QuickLook.common (GPL).

**Comment by xupefei** [comment] 2021-01-04 19:06
@mooflu Good point. I'll update QuickLook.Common to use MIT. Then @adyanth can update the submodule.

**Comment by adyah-cisco** [comment] 2021-01-05 07:09
I still see both QuickLook.Common and the Hello world example still on MIT. Should I update this plugin to GPL? @mooflu Feel free to create your own repo if you need to, and I will fork from yours. I wanted to keep track of any changes I do, so created a repo.

**Comment by adyanth** [comment] 2021-01-05 07:10
I still see both QuickLook.Common and the Hello world example still on MIT. Should I update this plugin to GPL? @mooflu Feel free to create your own repo if you need to, and I will fork from yours. I wanted to keep track of any changes I do, so created a repo.

**Comment by xupefei** [comment] 2021-01-05 09:29
@adyanth I updated QuickLook.Common from GPL to MIT. HelloWorld is already on MIT. So you have to update the submodule in the FolderViewer so that your code references to the MIT version of QuickLook.Common.

**Comment by kak8gm** [comment] 2021-01-19 08:11
A folder preview nice concept I came upon browsing [reddit](https://www.reddit.com/r/Windows_Redesign/comments/ksdp49/inspired_a_bit_by_quick_look_on_macos_when_the/). Would be nice to see it or some alteration of it implemented into this plugin.
![Folder preview](https://user-images.githubusercontent.com/71850180/105006012-bc62dd00-5a3e-11eb-8d4e-643fff9342ab.PNG)

**Comment by adyanth** [comment] 2021-04-08 15:55
@mooflu would you like to add it to the official plugin list? I have been using it for around 3 months now without issues! Once done, I guess this issue can be closed.

**Comment by rabelux** [comment] 2021-04-11 11:27
Please correct me if I'm wrong, but I think there are two kinds of plugins. One are "internal" plugins that get shipped with QL, the others are "external" ones that need to be downloaded and installed. You @adyanth built an external plugin whereas @mooflu's approach need's to get merged to be be included. Did I get that right?

**Comment by adyanth** [comment] 2021-04-11 11:33
Correct, I extracted the changes by @mooflu to an external plugin so that I can test it, and as per @xupefei 's point 2 [here](https://github.com/QL-Win/QuickLook/issues/575#issuecomment-753596366).

**Comment by rabelux** [comment] 2021-09-20 13:21
I'll close this and refer to adyanth's solution with an installable plugin available [here](https://github.com/adyanth/QuickLook.Plugin.FolderViewer).

**Closed by rabelux** 2021-09-20 13:21 UTC
Labels: duplicate, good for a plugin
