### ISSUE TITLE
Option to not open changelog when updating

### ISSUE THREAD

**Issue by LoganDark** [QL-Win/QuickLook#1166] opened 2022-08-02 15:36 UTC
Every once in a while QuickLook opens a window with a changelog to say it's updated, this is annoying and unnecessary and I don't care when it updates, only that it's available when I want to preview a file. Please provide an option to disable this.

**Comment by rabelux** [comment] 2022-08-02 19:15
Duplicate of #1109

**Closed by rabelux** 2022-08-02 19:15 UTC
