### ISSUE TITLE
When a file is selected and the space bar is pressed, it will automatically jump to the next file and open the preview.

### ISSUE THREAD

**Issue by AUENDXYZ** [QL-Win/QuickLook#1095] opened 2022-03-03 10:27 UTC
### When a file is selected and the space bar is pressed, it will automatically jump to the next file and open the preview. 

**Unless this is the only file in the folder in which this file resides, this problem will occur.**

If there are multiple files in the folder, usually jump to the next two or three files open and preview.

Please give guidance on how to correct this problem. 
Thank you!

**Comment by rabelux** [comment] 2022-03-03 14:00
Duplicate of #726

**Closed by rabelux** 2022-03-03 14:00 UTC
