### ISSUE TITLE
Quicklook in windows 11 causes stutter while dragging any window

### ISSUE THREAD

**Issue by smallg0at** [QL-Win/QuickLook#982] opened 2021-08-30 00:30 UTC
**Describe the bug**
If quicklook preview window is present, every single window will lag on drag.

**To Reproduce**
1. Start Quicklook
2. Open a image preview window
3. try to drag any window on screen => stutter
4. Close the preview window
5. try to drag any window on screen => no issue

**Desktop (please complete the following information):**
 - OS Version: Windows Insider Preview 22000.168 
 - QuickLook Version: 3.6.11.0, Store

**Screenshots and Exception Log**
No logs can be found at the user data folder.

**Comment by rabelux** [comment] 2021-08-30 06:22
Duplicate of #955. See https://github.com/QL-Win/QuickLook/issues/955#issuecomment-880445700.

**Closed by rabelux** 2021-08-30 06:22 UTC
