### ISSUE TITLE
Quicklook popup broken after upgrading to Windows 11

### ISSUE THREAD

**Issue by Cyberdroid1** [QL-Win/QuickLook#955] opened 2021-07-11 06:04 UTC
**Describe the bug**

After upgrading to Windows 11 Dev Insider, I noticed that the Quicklook popup is very buggy. It takes a long time for displaying info and previews correctly. Even the buttons on the top left and top right look weird. Plus, the cursor starts having a laggy motion when the popup is open. 

I also noticed that this bug only happened when the quicklook popup was opened from File explorer. When i tried quicklook-ing a file on my Desktop, the popup opened just normally.

**To Reproduce**

1. Upgrade to Win11 Dev insider from Win10
2. Try opening quicklook for a folder or an image
3. See error

**Expected behavior**

The quicklook popup should properly display the information and/or image normally.

**Desktop (please complete the following information):**

 - OS Version: Windows 11 Dev Insider 22000.65
 - QuickLook Version: 3.6.11 from MS Store

**Screenshots and Exception Log**

![image](https://user-images.githubusercontent.com/51435948/125183861-46923e00-e237-11eb-823a-b2995e64be07.png)

![image](https://user-images.githubusercontent.com/51435948/125183870-5c076800-e237-11eb-86e9-653c9ebcba43.png)

https://user-images.githubusercontent.com/51435948/125184467-b4d8ff80-e23b-11eb-800e-28e25b26de5b.mp4

**Comment by xupefei** [comment] 2021-07-12 07:55
I tend to believe it's a Windows bug. I'll wait for a few more builds before spending time fixing it.

**Comment by Y4shSHD** [comment] 2021-07-15 06:55
> I tend to believe it's a Windows bug. I'll wait for a few more builds before spending time fixing it.

Even I believe it's a Windows 11 Problem. Because as I "preview" my files, and keep QL on top, then drag the currently open window, the movement lags a LOT!

Check the screen recording attached, you'll know what I am saying!

https://user-images.githubusercontent.com/9900192/125742885-e077a041-70ba-4de2-8190-45d463f6e545.mp4

**Comment by ikas-mc** [comment] 2021-07-16 04:39
It's not just quicklook that has this problem.
It may be caused by the windows11's rendering of blur.
Turning off the system transparency and turning off the App blur effect can temporarily solve the problem. 
Test on 22000.71

**Comment by Masterlovsky** [comment] 2021-07-18 08:50
When I open a folder, quicklook render like this... Something wrong happend on system win11? 
![Snipaste_2021-07-18_16-50-23](https://user-images.githubusercontent.com/45965357/126061440-3be81e30-f0b1-4832-bef7-6a0f3148129a.jpg)

**Comment by Marocco2** [comment] 2021-07-18 10:04
> 
> 
> It's not just quicklook that has this problem.
> It may be caused by the windows11's rendering of blur.
> Turning off the system transparency and turning off the App blur effect can temporarily solve the problem.
> Test on 22000.71

How did you disable app blur effect? Disabling via system setting won't fix the problem

**Comment by ikas-mc** [comment] 2021-07-18 15:24
@Marocco2 
You need to modify the code and then build
https://github.com/QL-Win/QuickLook/blob/0dd8e919cab561185cc42006949e5294597c598b/QuickLook/ViewerWindow.xaml.cs#L106

**Comment by Marocco2** [comment] 2021-07-18 16:06
> @Marocco2 
> You need to modify the code and then build
> https://github.com/QL-Win/QuickLook/blob/0dd8e919cab561185cc42006949e5294597c598b/QuickLook/ViewerWindow.xaml.cs#L106
> 

Thanks, gonna try it ASAP

**Comment by ikas-mc** [comment] 2021-07-24 06:38
The api [SetWindowCompositionAttribute] is broken on win10(1903+) and win11, maybe we need to stop using this api, or add a option to disable blur...
It will not only cause problems in the app itself, but also cause problems in other windows
https://github.com/sourcechord/FluentWPF/issues/42
https://github.com/File-New-Project/EarTrumpet/issues/349
@xupefei

**Comment by Cyberdroid1** [comment] 2021-07-24 09:08
> or add a option to disable blur

i am in total support for adding option to disable blur.

**Comment by stem2580** [comment] 2021-07-25 16:11
this doesn't happen using [Files](https://github.com/files-community/Files), I suggest using it as an alternative until microsoft provides a fix

**Comment by ikas-mc** [comment] 2021-07-26 08:15
> this doesn't happen using [Files](https://github.com/files-community/Files), I suggest using it as an alternative until microsoft provides a fix

Files use win32 host  a standard  uwp project,so files does not use the internal api...

**Comment by geetanshpancholi** [comment] 2021-07-26 08:27
> @Marocco2
> You need to modify the code and then build
> https://github.com/QL-Win/QuickLook/blob/0dd8e919cab561185cc42006949e5294597c598b/QuickLook/ViewerWindow.xaml.cs#L106

Can u tell me how to do that??

**Comment by rabelux** [comment] 2021-07-26 09:09
> > @Marocco2
> > You need to modify the code and then build
> > https://github.com/QL-Win/QuickLook/blob/0dd8e919cab561185cc42006949e5294597c598b/QuickLook/ViewerWindow.xaml.cs#L106
> 
> Can u tell me how to do that??

Explained in the wiki

**Comment by DiegoMagdaleno** [comment] 2021-07-26 14:55
Maybe quicklook should migrate to the new Mika material instead of blur?

**Comment by Fytuf** [comment] 2021-07-30 06:25
Interesting, this bug only seems to happen in the NEW Explorer. It works perfectly fine on Files UWP, the desktop, and the old ribbon explorer.

**Comment by xupefei** [comment] 2021-07-31 21:52
Added a workaround to Nightly, please use it until MS fixed this issue: https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations#enabledisable-window-transparency-since-v3611-23.

**Comment by Cyberdroid1** [comment] 2021-08-01 13:29
I installed the nightly build and disable transparency via config, and its working normally now! 🎉 

But it has these ugly white pixels in the corners, but I guess this is an issue on MS' side, since I have seen this with other apps too.

![image](https://user-images.githubusercontent.com/51435948/127772624-6978d444-d67c-45b1-a0f8-f57f3b8cfde3.png)

**Comment by xupefei** [comment] 2021-08-02 12:08
The white border pixels might comes from the window border. I'll look into it later.

**Comment by Schlave** [comment] 2021-08-05 19:22
White artefacts seems to be fixed with nightly build + transparency disabled + latest Windows 11 preview build (Build 22000.120) just released today. Just tried it.
![Screenshot 2021-08-06 031934](https://user-images.githubusercontent.com/8032313/128408768-1e90d4fb-2311-4bbe-b1bf-2fae2db56e86.jpg)

They mentioned it in the fixes: "We've done some work to remove the unexpected white artifacts in the corners of windows when using dark mode."

**Comment by OfficialAwesomeDude** [comment] 2021-08-11 02:37
also not working for me, same problems

**Comment by xupefei** [comment] 2021-08-11 07:39
> also not working for me, same problems

Have you check this comment above?

> Added a workaround to Nightly, please use the Nightly version plus [this config](https://github.com/QL-Win/QuickLook/wiki/Advanced-configurations#enabledisable-window-transparency-since-v3611-23), until MS fixed this issue.

**Comment by Linger233** [comment] 2021-08-13 02:09
Maybe Quicklook's Transparency and win11's  new effect are not compatible.

**Comment by OpenWaygate** [comment] 2021-08-16 07:14
I have installed the nightly version on 22000.132 but not modify the transparency settings, the preview window appears right after I start quicklook, but several hours later I press <kbd>space</kbd> nothing hapens, I have to restart quicklook.

**Comment by xupefei** [comment] 2021-08-16 08:39
> I have installed the nightly version on 22000.132 but not modify the transparency settings, the preview window appears right after I start quicklook, but several hours later I press space nothing hapens, I have to restart quicklook.

You have to modify the transparency flag in the nightly version. Of course you'll have a problem if you don't do that.

**Comment by NFLS-1963** [comment] 2021-09-03 02:35
Same.

**Comment by WhiteNervosa** [comment] 2021-09-04 16:25
I felt like an idiot looking on Appveyor for awhile but it seems the nightly build expired for being a month old.

Can it be bumped or am I missing it, elsewhere?

**Comment by Void48** [comment] 2021-09-06 23:26
Nightly builds expired :/

**Comment by xupefei** [comment] 2021-09-07 08:04
@WhiteNervosa @Void48 
New build: https://ci.appveyor.com/project/xupefei/quicklook/build/artifacts

I'll release a new version this weekend.

**Comment by NFLSCode** [comment] 2021-09-07 08:06
@xupefei thanks.

**Comment by Zbynius** [comment] 2021-09-14 09:52
Which weekend is it about?

**Comment by xzayn** [comment] 2021-09-15 06:39
can you make it possible to subscribe to nightly builds within the app (like ShareX)? or on ms store thru signup emails(like Xodo PDF and Files by Yair)? or a separate Quicklook nightly on the store?(like Windows Terminal/myTube)

**Comment by xzayn** [comment] 2021-09-15 06:51
Also quicklook doesnt seem to work with Everything 1.5a (voidtools)

**Comment by rabelux** [comment] 2021-09-15 13:52
> can you make it possible to subscribe to nightly builds within the app (like ShareX)? or on ms store thru signup emails(like Xodo PDF and Files by Yair)? or a separate Quicklook nightly on the store?(like Windows Terminal/myTube)

Just subscribe/watch this project on github and you'll get emails on commits which cause new nightly builds.

**Comment by xupefei** [comment] 2021-09-15 16:56
> @xupefei Which weekend is it about?

Maybe _this_ weekend... I'm now moving, so I don't know when I can unpack & setup my developing rig.

**Comment by xzayn** [comment] 2021-09-17 18:06
No updates for quite some time...

**Comment by Zbynius** [comment] 2021-09-17 18:10
@xzayn Be patient! The developer is already working on it. It's a matter of a few days. The temporary solution (nightly version) works OK.

**Comment by xupefei** [comment] 2021-09-20 07:43
Fixed in Version 3.7.0.

**Closed by xupefei** 2021-09-20 07:43 UTC
