### ISSUE TITLE
Can't open on win 10 1903. It's just a white rectangle.

### ISSUE THREAD

**Issue by 888zhima** [QL-Win/QuickLook#512] opened 2019-06-14 08:53 UTC
After I press the Spacebar, just a white rectangle appeared. It can't open the file (.jpg .pdf .mkv ……) normally.
The picture just looks like this.
I love QuickLook, so I really expect a reply. 
Thanks a lot.

![the pic](https://user-images.githubusercontent.com/45889843/59496541-3c6cac80-8ec4-11e9-8d06-0efda7a4b851.PNG)

**Comment by xupefei** [comment] 2019-06-22 13:14
Closed as a duplicate of #442.
You are welcomed to post the debug report! See #442 for details.

**Closed by xupefei** 2019-06-22 13:14 UTC
