### ISSUE TITLE
Animated WEBP files

### ISSUE THREAD

**Issue by NaitorStudios** [QL-Win/QuickLook#1324] opened 2023-06-20 15:38 UTC
*For all's convenience, please use English to fill this issue.*

**Is your feature request related to a problem? Please describe.**
Animated WEBP files will just preview as a static image.

**Describe the solution you'd like**
Please update the image plugin to work with animated WEBP files.

**Describe alternatives you've considered**
Making a plugin or software myself, but I'm not familiar with C#.

**Additional context**
Nothing else.

**Comment by rabelux** [comment] 2023-06-23 12:22
Duplicate of #1024

**Closed by rabelux** 2023-06-23 12:22 UTC

**Comment by emako** [comment] 2024-12-30 09:07
Done, BUT Limitations: Only supports x64 systems.

Check it out in nightly build.
https://github.com/QL-Win/QuickLook/releases
