### ISSUE TITLE
Explorer "start searching" keybind obscures QuickLook

### ISSUE THREAD

**Issue by AndreaTerenz** [QL-Win/QuickLook#1110] opened 2022-03-19 16:39 UTC
**Describe the bug**
I've just installed QuickLook on Windows 11 (build 22000.556). It works fine in the Desktop, but within Explorer it almost never launches because the spacebar seems to already be bound to a "quick search" function; in other words, by pressing space in Explorer you can start typing some search query in whatever folder you happen to be at the moment, and that completely obscures QuickLook. I've tried to find keybind settings for both Explorer and QuickLook but I've had no luck.

**To Reproduce**
1. Install QL on Win11
2. Open Explorer
3. Try to run QL on any file or folder

**Expected behavior**
The search bar in the upper right corner of the window will be activated and start receiving keypresses to get a search query (instead of launching QL).

**Desktop (please complete the following information):**
 - OS Version: Windows 11 build 22000.556
 - QuickLook Version: 3.7.10 from Win Store

**Comment by rabelux** [comment] 2022-03-19 16:46
Duplicate of #798

**Closed by rabelux** 2022-03-19 16:46 UTC
