### ISSUE TITLE
can't view the preview for .psb files

### ISSUE THREAD

**Issue by apierre55000** [QL-Win/QuickLook#938] opened 2021-06-17 12:34 UTC
hello all,
i use photoshop all days and i saw that i can't preview files .psb it's possible to add this extension into quicklook ?

thank you :)

**Comment by rabelux** [comment] 2021-06-17 12:44
Duplicate of #768. Please search for existing issues next time. Should be solved in the nightly version.

**Closed by rabelux** 2021-06-17 12:44 UTC
