### ISSUE TITLE
Waveform view for audio files

### ISSUE THREAD

**Issue by barbarojacp** [QL-Win/QuickLook#957] opened 2021-07-15 02:09 UTC
It is very much needed when selecting samples or music
Just an (optional) waveform view on the top of the window would suffice.
There is a software from audioease called snapper that works beautifully but only on mac. Also lets you convert formats and extract sections but that could be aout of the scope of QL.
[https://www.audioease.com/snapper/#](url)

**Comment by rabelux** [comment] 2021-07-15 21:43
Duplicate of #642

**Closed by rabelux** 2021-07-15 21:43 UTC
