### ISSUE TITLE
High RAM usage?

### ISSUE THREAD

**Issue by Darthagnon** [QL-Win/QuickLook#344] opened 2018-09-06 13:51 UTC
Issue
-----
Idling, QuickLook takes between 100~150 MB RAM, which is almost as much as Windows Explorer (when I took the screenshot, I had 3 Explorer windows open, using Ejie Clover for tabs). It jumps up to 190 MB (previewing simple Excel spreadsheet), then went to idling at 183 MB. I have both currently available plugins installed, and am using the MSI version, v0.3.6.1
![2018-09-06 14_41_52-task manager](https://user-images.githubusercontent.com/20792748/45161208-333b0a80-b1e3-11e8-9fa3-6d89a30d9d1b.png)

Don't want to sound like I'm complaining too hard, and I know RAM isn't as much of an issue these days, but having only just upgraded from a 4GB laptop, I'm still very concious about RAM usage (e.g. my antivirus, Panda, takes up about 25MB RAM while idling). As there were no RAM issues open, I just thought I'd post...

**Comment by xupefei** [comment] 2018-09-06 14:56
It is normal. 
Some of the RAM is occupied by plugins for faster loading in the future (You can feel this by comparing the loading time of first- and second-time previewing). They will be released automatically when long time idle or under memory pressure.

**Comment by Darthagnon** [comment] 2018-09-06 15:31
After I restarted QuickLook, it went back to ~45 MB, then up to 75~80 MB after previewing a few files, videos, etc.

**Comment by xupefei** [comment] 2018-09-06 15:35
It's normal.

**Comment by Joaxin** [comment] 2018-09-11 05:51
Indeed after I previewed some PPTs & Excels & PDFs & Videos, it jumped to about 650M RAM used.

**Comment by xupefei** [comment] 2018-09-11 10:36
Try previewing other files and see if it releases the RAM.

**Comment by iamsunxing** [comment] 2018-10-08 12:11
![in my computer](https://raw.githubusercontent.com/iamsunxing/images/master/2.bmp)

**Comment by rabelux** [comment] 2021-03-29 11:03
I'll close this as this is no issue and intended behaviour

**Closed by rabelux** 2021-03-29 11:03 UTC
