### ISSUE TITLE
Photo color management

### ISSUE THREAD

**Issue by giovariot** [QL-Win/QuickLook#1191] opened 2022-10-10 14:49 UTC
**Is your feature request related to a problem? Please describe.**
When I preview photos through quicklook the colors look oversaturated compared to how they look in Windows 11 photo viewer

**Describe the solution you'd like**
It would be nice if the preview respected the color profile of windows photo viewer which apparently currently show more precise color

**Comment by rabelux** [comment] 2022-10-10 17:01
Duplicate of #329.
Try the nightly and adjust your config if you want to test it.
Details: https://github.com/QL-Win/QuickLook/issues/329#issuecomment-1038151099

**Closed by rabelux** 2022-10-10 17:01 UTC
