### ISSUE TITLE
ImageViewer don't remember theme settings

### ISSUE THREAD

**Issue by mezhgano** [QL-Win/QuickLook#720] opened 2020-08-09 14:32 UTC
It will be nice for overall consistency to add a Light Theme, or maybe just respect the system preferred color (Dark or Light)
BTW, the app is great!

**Comment by xupefei** [comment] 2020-08-09 14:41
Sorry I didn't get it. Are you talking about QuickLook? It already has a light theme.

**Comment by mezhgano** [comment] 2020-08-09 14:44
Wow, sorry, i didn't know it, where i can read about or just turn it on?

**Comment by xupefei** [comment] 2020-08-09 16:45
There is a semi-transparent switching icon at the top-right corner of the image viewer.

**Comment by mezhgano** [comment] 2020-08-09 18:40
Eeeh, didn't noticed, thanks!

**[SOLVED]**

**Comment by xupefei** [comment] 2020-08-10 08:49
It's already remembering the theme afaik: https://github.com/QL-Win/QuickLook/blob/master/QuickLook.Plugin/QuickLook.Plugin.ImageViewer/Plugin.cs#L80

Is it not working for you?

**Comment by mezhgano** [comment] 2020-08-10 09:47
Unfortunally, nope
Installed it as usual, to default **AppData** folder

**Comment by xupefei** [comment] 2020-08-16 10:25
Really strange as it works for me. What operating system do you use?

If you want, you can clean up the config of ImageViewer and see if it remembers your light/dark setting.

**Comment by mezhgano** [comment] 2020-08-16 12:47
I'm on latest **19041.450** Windows 10
I assume that config file for ImageViewer located in 
```
C:\Users\Username\AppData\Roaming\pooi.moe\QuickLook\QuickLook.Plugin.ImageViewer.config
```
If its right, then my config file is already pretty empty:
```
<?xml version="1.0" encoding="utf-8"?><Settings />
```

So, i cleaned up the contents of config, open random image, select Light Theme, but got Dark Theme by default again after reopening any image. 

Seems like Dark Theme is default value? 
Maybe i need manually select Light Theme in config, whats the syntax?

**Comment by xupefei** [comment] 2020-08-16 15:26
Try this:
```
<?xml version="1.0" encoding="utf-8"?>
<Settings>
  <LastTheme>2</LastTheme>
</Settings>
```

**Comment by xupefei** [comment] 2020-08-16 15:28
Btw, are you using the latest version, which is 3.6.9?

**Comment by mezhgano** [comment] 2020-08-16 15:36
Now it works, thanks a lot!
Yes, version is 3.6.9, installed it right after clean Windows installation.

P.S. Don't know should i close this issue or keep, because maybe its some kind of Windows bug.

**Comment by xupefei** [comment] 2020-08-16 18:53
I think we can close this issue since it seems unreproducible :)

**Closed by xupefei** 2020-08-16 18:53 UTC

**Comment by moriel5** [comment] 2020-08-18 02:08
I can confirm that the same issue happens for me.
I am using the latest unstable version, portably, on Windows 10 LTSC 2019 (1809), fully updated.

**Comment by xupefei** [comment] 2020-08-18 07:56
> I can confirm that the same issue happens for me.
> I am using the latest unstable version, portably, on Windows 10 LTSC 2019 (1809), fully updated.

Could you create a new ticket so we can discuss it there?

**Comment by moriel5** [comment] 2020-08-18 10:09
@xupefei No problem.
